zuul:
  routes:
    test:
      path: /test/**
      stripPrefix: false
      serviceId: test-service

ribbon:
  eureka:
    enabled: true

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/